### ISSUE TITLE
Multiple Issues on the ASG Handler

### ISSUE THREAD

**Issue by markedcahinde** [fortinet/fortigate-autoscale-aws#9] opened 2020-10-07 12:33 UTC
Hi,
I have been poking around the setup and looking for a reason on why the cluster is getting replaced frequently. I have tried updating the timeouts, and heartbeat loss count but to no avail. 

Currently, my setup is being replaced every 15 mins or so. Even without me tweaking anything around. I found the following from the Cloudwatch logs

2020-10-07T10:18:18.912Z	57daa02a-deb5-4071-a4ea-bb6b5bb7eb91	ERROR	error in forceOutOfSync(). Error: Cannot read property 'syncState' of undefined Error stack:TypeError: Cannot read property 'syncState' of undefined
    at t.ConstantIntervalHeartbeatSyncStrategy.forceOutOfSync (/var/task/index.js:1:278962)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async N.handleTerminatingVm (/var/task/index.js:1:101949)
    at async N.handleTerminatingVm (/var/task/index.js:14:48570)
    at async N.handleAutoscaleRequest (/var/task/index.js:1:281595)
    at async Runtime.t.scheduledEventHandler [as handler] (/var/task/index.js:14:40397)

Above logs came from the autoscaling event lambda. I can't quite pin point where the issue is and why my cluster gets replaced very frequent. See my Launch times below 

<img width="307" alt="image" src="https://user-images.githubusercontent.com/3380853/95331273-5661a800-08dc-11eb-8e01-bc96230a531f.png">

**Comment by JaydenLiang** [comment] 2020-10-07 17:50
@markedcahinde Can you please collect more logs for us to diagnose the problem? Better collect logs range from 2 minutes before that error (2020-10-07T10:18:18.912Z) to 1 minute after, time-wise. You can mask any information you don't want to expose in the logs by the **<MASK>** place holder so that we understand it the same way.

Can you please send your logs to github@fortinet.com including the following information:

the link to this GitHub open issue: https://github.com/fortinet/fortigate-autoscale-aws/issues/9

information about your stack:
1. BYOL auto scaling group minsize/capacity/maxsize
2. PAYG auto scaling group minsize/capacity/maxsize
3. how many BYOL license files you provided with the stack
4. Heartbeat loss count
5. Heartbeat interval
6. the value of the timeout you mentioned and which timeout you meant (there are two settings of timeout)

Apart from the above, could you please let me know the way you update the "timeouts, and heartbeat loss count but to no avail."? You can reply directly to this message here with your answer.

**Comment by markedcahinde** [comment] 2020-10-07 18:28
Hi @JaydenLiang ,
I have sent the email already.

I have tried updating the following from their default value
LifecycleHookTimeout – 900 secs
HeartBeatDelayAllowance – 5 secs
FgtAsgHealthCheckGracePeriod - 900 secs

We have shifted from a pure OnDemand solution to a Hybrid one. I have been encountering this issue before where the whole cluster is being replaced, but only when we moved to Hybrid that it became more frequent. I dug in and saw the undefined syncState error in auto scale event lambda logs.

I have also noticed that the host does not push through CompleteLifeCycle Action even after a successful run of the autoscale handler lambda. Perhaps it was the reason behind the replacement, which makes me that I have two different issues.
1. Not updating to CompleteLifeCycle Action and LifeCycle times out
2. undefined syncState error

**Comment by markedcahinde** [comment] 2020-10-07 18:37
To support the claim of successful Autoscale Handler run, please see cloudinit debug below

>> FGVM02TM20011462 # diagnose debug cloudinit show
 >> Checking metadata source aws
 >> Cloudinit curl header: Fos-instance-id: MASK
 >> Cloudinit trying to get license from: https://MASK.execute-api.ap-southeast-1.amazonaws.com/prod/byol-license
 >> Cloudinit download license successfully
 >> Cloudinit trying to get config script from: https://MASK.execute-api.ap-southeast-1.amazonaws.com/prod/fgt-as-handler
 >> Cloudinit download config script successfully
 >> Trying to install vmlicense ...
 >> Run config script
 >> Finish running script
 >> FGVM02TM20011462 $  config sys interface
 >> FGVM02TM20011462 (interface) $      edit "port2"
 >> FGVM02TM20011462 (port2) $          set mode dhcp
 >> FGVM02TM20011462 (port2) $          set allowaccess ping https ssh http fgfm
 >> FGVM02TM20011462 (port2) $      next
 >> FGVM02TM20011462 (interface) $  end
 >> FGVM02TM20011462 $
 >> FGVM02TM20011462 $  config router static
 >> FGVM02TM20011462 (static) $      edit 1
 >> FGVM02TM20011462 (1) $          set dst 10.152.0.0/25
 >> FGVM02TM20011462 (1) $          set device "port2"
 >> FGVM02TM20011462 (1) $          set dynamic-gateway enable
 >> FGVM02TM20011462 (1) $      next
 >> FGVM02TM20011462 (static) $  end
 >> FGVM02TM20011462 $  config system dns
 >> FGVM02TM20011462 (dns) $      unset primary
 >> FGVM02TM20011462 (dns) $      unset secondary
 >> FGVM02TM20011462 (dns) $  end
 >> FGVM02TM20011462 $  config system global
 >> FGVM02TM20011462 (global) $      set admin-sport 8443
 >> FGVM02TM20011462 (global) $  end
 >> FGVM02TM20011462 $  config system auto-scale
 >> FGVM02TM20011462 (auto-scale) $      set status enable
 >> FGVM02TM20011462 (auto-scale) $      set sync-interface "port1"
 >> FGVM02TM20011462 (auto-scale) $      set hb-interval 90
 >> FGVM02TM20011462 (auto-scale) $      set role master
 >> FGVM02TM20011462 (auto-scale) $      set callback-url https://MASK.execute-api.ap-southeast-1.amazonaws.com/prod/fgt-as-handler
 >> FGVM02TM20011462 (auto-scale) $      set psksecret MASK
 >> FGVM02TM20011462 (auto-scale) $  end
 >> FGVM02TM20011462 (auto-scale) $
 >> FGVM02TM20011462 (auto-scale) $  config firewall address
 >> FGVM02TM20011462 (auto-scale) $      edit internal-elb-web
 >> FGVM02TM20011462 (auto-scale) $          set type fqdn
 >> FGVM02TM20011462 (auto-scale) $          set fqdn "MASK.elb.ap-southeast-1.amazonaws.com"
 >> FGVM02TM20011462 (auto-scale) $          set associated-interface "port1"
 >> FGVM02TM20011462 (auto-scale) $      next
 >> FGVM02TM20011462 (auto-scale) $      edit "private-subnet-egress"
 >> FGVM02TM20011462 (auto-scale) $          set associated-interface "port2"
 >> FGVM02TM20011462 (auto-scale) $      next
 >> FGVM02TM20011462 (auto-scale) $  end
 >> FGVM02TM20011462 (auto-scale) $
 >> FGVM02TM20011462 (auto-scale) $  config firewall vip
 >> FGVM02TM20011462 (auto-scale) $      edit internal-web
 >> FGVM02TM20011462 (auto-scale) $          set type fqdn
 >> FGVM02TM20011462 (auto-scale) $          set mapped-addr internal-elb-web
 >> FGVM02TM20011462 (auto-scale) $          set portforward enable
 >> FGVM02TM20011462 (auto-scale) $          set extintf port1
 >> FGVM02TM20011462 (auto-scale) $          set extport 443
 >> FGVM02TM20011462 (auto-scale) $          set mappedport 443
 >> FGVM02TM20011462 (auto-scale) $      next
 >> FGVM02TM20011462 (auto-scale) $  end
 >> FGVM02TM20011462 (auto-scale) $
 >> FGVM02TM20011462 (auto-scale) $  config firewall policy
 >> FGVM02TM20011462 (auto-scale) $      edit 0
 >> FGVM02TM20011462 (auto-scale) $          set name "internal-web-HTTPS-ingress"
 >> FGVM02TM20011462 (auto-scale) $          set srcintf "port1"
 >> FGVM02TM20011462 (auto-scale) $          set dstintf "port2"
 >> FGVM02TM20011462 (auto-scale) $          set srcaddr "all"
 >> FGVM02TM20011462 (auto-scale) $          set dstaddr "internal-web"
 >> FGVM02TM20011462 (auto-scale) $          set action accept
 >> FGVM02TM20011462 (auto-scale) $          set schedule "always"
 >> FGVM02TM20011462 (auto-scale) $          set service "HTTPS"
 >> FGVM02TM20011462 (auto-scale) $          set fsso disable
 >> FGVM02TM20011462 (auto-scale) $          set nat enable
 >> FGVM02TM20011462 (auto-scale) $      next
 >> FGVM02TM20011462 (auto-scale) $      edit 0
 >> FGVM02TM20011462 (auto-scale) $          set name "allow-private-subnet-egress"
 >> FGVM02TM20011462 (auto-scale) $          set srcintf "port2"
 >> FGVM02TM20011462 (auto-scale) $          set dstintf "port1"
 >> FGVM02TM20011462 (auto-scale) $          set srcaddr "private-subnet-egress"
 >> FGVM02TM20011462 (auto-scale) $          set dstaddr "all"
 >> FGVM02TM20011462 (auto-scale) $          set action accept
 >> FGVM02TM20011462 (auto-scale) $          set schedule "always"
 >> FGVM02TM20011462 (auto-scale) $          set service "ALL"
 >> FGVM02TM20011462 (auto-scale) $          set fsso disable
 >> FGVM02TM20011462 (auto-scale) $          set nat enable
 >> FGVM02TM20011462 (auto-scale) $      next
 >> FGVM02TM20011462 (auto-scale) $  end
 >> FGVM02TM20011462 (auto-scale) $

**Comment by JaydenLiang** [comment] 2020-10-08 04:57
@markedcahinde thanks for the information. We will firstly try to reproduce the issue on our side and then reach out to you again.

**Comment by markedcahinde** [comment] 2020-10-08 07:43
Thanks. Please take note that even on 6.2.3 AMI, the issue persists.

**Comment by JaydenLiang** [comment] 2020-11-05 01:36
> Thanks. Please take note that even on 6.2.3 AMI, the issue persists.

Hi @markedcahinde , we have issued a commit that resolves this issue. It's in the branch: https://github.com/fortinet/fortigate-autoscale-aws/tree/patch_3.1.1

Please feel free to try it out before it comes into the next release.

**Comment by markedcahinde** [comment] 2020-11-05 14:37
Thank you! I'll take a look into it :) Will the next release include the latest 6.4 patch?

**Comment by markedcahinde** [comment] 2020-11-09 16:35
Hi @JaydenLiang ,
I have tried the latest patch, and while the previous exceptions are nowhere to be found yet, I can't seem to see the autoscaling group in finishing the lifecyle hook.

I have adjusted the heartbeat timeout from 480 secs to 1200 secs already, but the problem persists. It seems that for the scale out hook, the default action was done since the heartbeat times out, which is ABANDON. Currently I'm using the BYOL option as I do have acquired an evaluation license.

1. How does the lifecycle hook for EC2_INSTANCE_LAUNCHING get updated to next status or CONTINUE?
2. Which resource creates the AWS api call for this?

**Comment by JaydenLiang** [comment] 2020-11-09 18:45
> I have tried the latest patch, and while the previous exceptions are nowhere to be found yet, I can't seem to see the autoscaling group in finishing the lifecyle hook.

Hi @markedcahinde , I noticed the instance launch unsuccessful event in your previous logs. Normally, the FortiGate instance should be spun up and become responding within the launch lifecycle hook timeout, based on a lot of test results we have done.

Could you please observe the full creation stage of a FortiGate instance in the EC2 console? When the autoscaling group starts to bring up an instance, the instance is in the pending:wait state. You can then find the instance in the EC2 console using the Instance Id, and see that it's provisioning. You can then get more information by 'get system logs' following [this instruction](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-console.html)

Meanwhile or in a moment, you can be able to log in to the FortiGate via ssh. Do a
`diag debug cloudinit show`
and check what it shows. If you don't see any output, probably because the cloudinit not yet started. You simply wait a moment and do the command again, repeat until you see something.

Hopefully you can figure out the reason your instance creation timed out. Let me know about your findings so we can better help you out.

**Comment by markedcahinde** [comment] 2020-11-10 16:00
Hi @JaydenLiang ,
Thanks for being patient on my issue.

So I followed your advise and observed the full cycle of autoscale provisioning. All essential logs can be found [here](https://gist.github.com/markedcahinde/18c0ccaacd3dd15c7d2c3d915d552971).

I have set the hearbeat timeout to 1200 secs for the hook, with 90 secs intervals in the config system auto-scale. I noticed that you are correct, the FortiGate instance could've been responsive within the lifecycle hook timeout. In fact, within 3 mins the instance is already accessible via SSH and has passed the target group health check.

All signs point to a healthy FortiGate instance, but for some reason, the lifecyle hook completion is not done. Can it be that the instance can't reach the handler after running the config script? Or can it be that the autoscale handler does not respond to heartbeat checks?

**Comment by JaydenLiang** [comment] 2020-11-12 19:26
> Hi @JaydenLiang ,
> Thanks for being patient on my issue.
> 
> So I followed your advise and observed the full cycle of autoscale provisioning. All essential logs can be found [here](https://gist.github.com/markedcahinde/18c0ccaacd3dd15c7d2c3d915d552971).
> 
> I have set the hearbeat timeout to 1200 secs for the hook, with 90 secs intervals in the config system auto-scale. I noticed that you are correct, the FortiGate instance could've been responsive within the lifecycle hook timeout. In fact, within 3 mins the instance is already accessible via SSH and has passed the target group health check.
> 
> All signs point to a healthy FortiGate instance, but for some reason, the lifecyle hook completion is not done. Can it be that the instance can't reach the handler after running the config script? Or can it be that the autoscale handler does not respond to heartbeat checks?

I replied to your [gist](https://gist.github.com/markedcahinde/18c0ccaacd3dd15c7d2c3d915d552971).

Are you able to collect more logs starting from 2020-11-10T15:14:22.025Z until the time when the lifecycle timedout?

there should be logs about "heartbeat sync" or you can lookup the keyword "handleHeartbeatSync".

those logs are also the key to identify the issue.

**Comment by markedcahinde** [comment] 2020-11-13 13:23
Hi @JaydenLiang,

I can't lookup such keyword on the autoscaling handler cloudwatch logs as there's no record of it. I was under the impression that those logs will show anytime after the config script successfully ran. I believe that it should be a part of the heartbeat to the handler right? However, besides not running the complete lifecycle call to the handler, no heartbeat calls are seen. 
Could this be an effect of the firewalls policies that affected the call to api gateway through private vpc endpoint?
I did not modified anything from base config that came with the deployment package.

Which interface calls the autoscaling handler and can it be that the connection is blocked or is routed somewhere else?

Please see the exact logs that follows the end of lambda_autoscale_handler_cloudwatch.log from my gist:

```
edit 0
        set name "allow-private-subnet-egress"
        set srcintf "port2"
        set dstintf "port1"
        set srcaddr "private-subnet-egress"
        set dstaddr "all"
        set action accept
        set schedule "always"
        set service "ALL"
        set fsso disable
        set nat enable
    next
end
--
2020-11-10T15:14:22.025Z	39fe86b3-0797-46a7-a3d1-86b07a3bc8f1	INFO	called handleBootstrap.
2020-11-10T15:14:22.025Z	39fe86b3-0797-46a7-a3d1-86b07a3bc8f1	INFO	called handleAutoscaleRequest.
END RequestId: 39fe86b3-0797-46a7-a3d1-86b07a3bc8f1
REPORT RequestId: 39fe86b3-0797-46a7-a3d1-86b07a3bc8f1	Duration: 5292.55 ms	Billed Duration: 5300 ms	Memory Size: 128 MB	Max Memory Used: 128 MB	Init Duration: 491.93 ms
START RequestId: 1cf965be-bf33-4e80-8809-cbe5ba044f35 Version: $LATEST
2020-11-10T15:35:53.536Z	1cf965be-bf33-4e80-8809-cbe5ba044f35	INFO	{  resource: '/fgt-as-handler',  path: '/fgt-as-handler',
  httpMethod: 'GET',
  headers: {
    Accept: '*/*',
```

As you can see, it's a call to the handler as a new instance is replacing the timed out instance from lifecycle hook. Also, rather than keeping it replacing hosts, I opted to disable the autoscaling group altogether and set everything to 0 after an hour.

**Comment by markedcahinde** [comment] 2020-11-13 14:24
Hi @JaydenLiang ,
I believe I have seen what's causing the non-update of LifeCycle Hook.
If you notice from the cloudinit output that the even at the very last part, it's still in config system auto-scale mode
```
 >> FGVM02<REDACTED> (auto-scale) $      edit 0
 >> FGVM02<REDACTED> (auto-scale) $          set name "allow-private-subnet-egress"
 >> FGVM02<REDACTED> (auto-scale) $          set srcintf "port2"
 >> FGVM02<REDACTED> (auto-scale) $          set dstintf "port1"
 >> FGVM02<REDACTED> (auto-scale) $          set srcaddr "private-subnet-egress"
 >> FGVM02<REDACTED> (auto-scale) $          set dstaddr "all"
 >> FGVM02<REDACTED> (auto-scale) $          set action accept
 >> FGVM02<REDACTED> (auto-scale) $          set schedule "always"
 >> FGVM02<REDACTED> (auto-scale) $          set service "ALL"
 >> FGVM02<REDACTED> (auto-scale) $          set fsso disable
 >> FGVM02<REDACTED> (auto-scale) $          set nat enable
 >> FGVM02<REDACTED> (auto-scale) $      next
 >> FGVM02<REDACTED> (auto-scale) $  end
 >> FGVM02<REDACTED> (auto-scale) $
```
I believe this is because of a quotation mark I have used as part of the psksecret . 
Apologies for missing this big time and wasting your time looking at it. 

I'm still looking out for the original syncState error, which I believe has been fixed in this patch?

**Comment by JaydenLiang** [comment] 2020-11-17 01:32
> Hi @JaydenLiang ,
> I believe I have seen what's causing the non-update of LifeCycle Hook.
> If you notice from the cloudinit output that the even at the very last part, it's still in config system auto-scale mode
> 
> ```
>  >> FGVM02<REDACTED> (auto-scale) $      edit 0
>  >> FGVM02<REDACTED> (auto-scale) $          set name "allow-private-subnet-egress"
>  >> FGVM02<REDACTED> (auto-scale) $          set srcintf "port2"
>  >> FGVM02<REDACTED> (auto-scale) $          set dstintf "port1"
>  >> FGVM02<REDACTED> (auto-scale) $          set srcaddr "private-subnet-egress"
>  >> FGVM02<REDACTED> (auto-scale) $          set dstaddr "all"
>  >> FGVM02<REDACTED> (auto-scale) $          set action accept
>  >> FGVM02<REDACTED> (auto-scale) $          set schedule "always"
>  >> FGVM02<REDACTED> (auto-scale) $          set service "ALL"
>  >> FGVM02<REDACTED> (auto-scale) $          set fsso disable
>  >> FGVM02<REDACTED> (auto-scale) $          set nat enable
>  >> FGVM02<REDACTED> (auto-scale) $      next
>  >> FGVM02<REDACTED> (auto-scale) $  end
>  >> FGVM02<REDACTED> (auto-scale) $
> ```
> 
> I believe this is because of a quotation mark I have used as part of the psksecret .
> Apologies for missing this big time and wasting your time looking at it.
> 
> I'm still looking out for the original syncState error, which I believe has been fixed in this patch?

yes the syncState error was fixed. Which quotation mark did you try with? single or double?

**Comment by markedcahinde** [comment] 2020-11-17 09:02
I think so too! I haven't been able to encounter the error since last week, I'll proceed with closing this issue after your comment. I did used a double quote in the psksecret and that's where my issues in syncing and lifecyle started.

**Comment by JaydenLiang** [comment] 2020-11-18 18:26
> I think so too! I haven't been able to encounter the error since last week, I'll proceed with closing this issue after your comment. I did used a double quote in the psksecret and that's where my issues in syncing and lifecyle started.

We have also reproduced the quotation marks issue ourselves and have a pending fix for it. We will close this issue as we rollout the new release. Let us take care of this open issue. Thanks!

**Comment by markedcahinde** [comment] 2020-11-20 10:23
Thank you very much @JaydenLiang! Looking forward for the fix :)

**Closed** 2020-12-03 19:12 UTC
